#!/usr/bin/env bash

# Set the docker command to use.
DOCKER="docker"

# Disable pseudo-TTY allocation for CI. The -T flag removes interaction.
TTY="-it"

# Travis CI provides a CI environment variable which can be used to check if
# this is running in a CI environment.
if [[ ${CI:-false} == "true" ]]; then
    TTY="-T"
fi

# Pass arguments to docker-compose, or default to docker-compose ps.
if [[ $# -gt 0  ]]; then
    case "$1" in

        store )
            shift 1
            ${DOCKER} run --rm ${TTY} \
                -v `pwd`:/var/www/html \
                -w /var/www/html \
                -e CF_SECRET_SERVICE=${CF_SECRET_SERVICE:-''} \
                -e CF_SECRET_SERVICE_KEY=${CF_SECRET_SERVICE_KEY:-''} \
                ubuntu:latest \
                bash .cloudfoundry/store_env.sh
            ;;

        deploy )
            shift 1
            ${DOCKER} run --rm ${TTY} \
                -v `pwd`:/var/www/html \
                -w /var/www/html \
                node:14 \
                bash .travis/deploy.sh
            ;;

        * )
            shift 1
            ${DOCKER} run --rm ${TTY} \
                -v `pwd`:/var/www/html \
                -w /var/www/html \
                ubuntu:latest \
                "$@"

    esac
fi
