#!/usr/bin/env bash

# Set script scope environment variables for dev or CI.
export CFN_TEMPLATE=${CFN_TEMPLATE:-cloudformation}

# Pass arguments to docker-compose, or default to docker-compose ps.
if [[ $# -gt 0  ]]; then
    case "$1" in

        # Run the Cloudformation generate command inside a new container
        cfn|cloudformation )
            docker-compose run --rm troposphere > aws/${CFN_TEMPLATE}.json
            cat aws/${CFN_TEMPLATE}.json
            ;;

        # Run a node command inside a new container
        npm )
            shift 1
            docker-compose run --rm ${TTY} \
                -w /var/www/html \
                -e WWWUID=${WWWUID} \
                admin \
                npm "$@"
            ;;

        # Run a docker-compose command
        * ) docker-compose "$@"; ;;

    esac
else
    docker-compose ps
fi
